### ISSUE TITLE
Can we have the cancer-specific train data?

### ISSUE THREAD

**Issue by nguyentr17** [EJIUB/ParsVNN#4]
Hi, I would like to experiment with the pruning algorithm. Can you upload one cancer-specific data you use to train? I'm fine with either cancer type.

**Comment by EJIUB** [comment]
I have uploaded a data folder.

**Comment by nguyentr17** [comment]
Thank you! Can you also add the LUNG_test data you used to test?

**Comment by EJIUB** [comment]
Added.
